{% set version = "1.8" %}

package:
  name: datamash
  version: {{ version }}

source:
  url: http://ftpmirror.gnu.org/datamash/datamash-{{ version }}.tar.gz
  sha256: 94a4e11819ad259aa3745b7eca392e385e3a676d276e8cbb616269dbbb17fe6d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - datamash --version
    - seq 1 10 | datamash sum 1

about:
  home: https://www.gnu.org/software/datamash/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: GNU datamash is a command-line program which performs basic numeric,textual and statistical operations on input textual data files.
  doc_url: https://www.gnu.org/software/datamash/manual/

extra:
  recipe-maintainers:
    - bgruening
    - rvalieris
