appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mDaes/ZxfUG4q55GgtyiBu1/KtKAIN8LRG1sIrF/AzO8PrQ05xtRuJWw6DNhl3JPgyLGbkvrKl+U6wkN18EE0LTMU2Qi9fWmUKACGb/JDLcHky7/h4FD9wiUwBwMw/2mysFIE4Pj0eKjIjKKDevFMSH6lhtisPw5kcwJ0oYYt9LfnP5o11FkB0UgKpw7Is80gUXCBX2ZywDJNrmGZbDHqaw/z78MJiJUis1MU2d5nptGv2AefFz95VdcO+ExbHWBQngjZcw1Tmklh45yEOXc1gjwfBUIz6xw0ayYokwCVhRglG8H/yLFwv4x6zazMZRopijfDVQ/wIw0tbR4Mvg00yQwLIVgk6GaDLOcD2O7IcYe65uZpBuVVBJcy8oJ2KaM6X3EyE0wujPg82Fiwv32XVkYYK0onV+2Y0uuuTN5vLrT+vKZMcDIfiLNWKIFh4LFo/jy03rRuJk4ApMgy7KkB3CohFz+AFeu6F6E3VSscPFLD1jwdDVuDMIst5F18ujjTOsSuG8Tekja7+YYL/TTtck25gKaNHpqMsHwoTRb2a2GpbTCj4AD/e5cpj21UgPySqAf+ACEIbWVlx1Pgk1VT9SRs6Auv+f+U/NAhLq3S928tdE+yXJ7zFeBqAUt+KpHDRDyx25SNXMXXRbPke2lQgi0pRU6dvvJNxFsY3D3d88=}
